### ISSUE TITLE
DagLoans

### ISSUE THREAD

**Issue by ilchec** [LingConLab/conlab-server-issues#12]
Project name: DagLoans
Project description: The DagLoans database contains results of elicitation of a list of 160 lexical meanings across languages of Daghestan. Data collection was aimed at assessing the amount of lexical transfer between these languages. The database includes the data on 23 languages (15 collected in the field, 7 provided by experts, 19 based on dictionaries). The data have been collected in 38 villages across Daghestan and 5 villages in the Qax district of Azerbaijan.
Tags (they are important for the later work on all projects): DagLoans, lexical convergence
Path to the project/interface: ichechuro/DagLoansHSEServer
Desired hostname: lingconlab.ru/dagloans
Software (leave blank, if you don't need it):

**Comment by leramorozova** [comment]
Сайт доступен по ссылке: http://lingconlab.ru/dagloans/
Если все в порядке, закройте, пожалуйста, заявку.
