### ISSUE TITLE
Hostname for a new corpus

### ISSUE THREAD

**Issue by enotikk** [LingConLab/conlab-server-issues#13]
Project name: Корпус говоров низовья рек Лух и Теза
Project description: 
Tags (they are important for the later work on all projects):
Path to the project/interface: /home/aazanova/Folklor
Desired hostname: lingconlab.ru/lukhteza
Software (leave blank, if you don't need it):

**Comment by kirillkoncha** [comment]
Все готово! http://lingconlab.ru/Folklor/

**Comment by anapanifica** [comment]
@kirillkoncha Но в заявке же было сказано, что адрес должен быть lingconlab.ru/lukhteza. Переделай, пожалуйста.

**Comment by kirillkoncha** [comment]
> @kirillkoncha Но в заявке же было сказано, что адрес должен быть lingconlab.ru/lukhteza. Переделай, пожалуйста.

Да, простите пожалуйста. Переделал.
