### ISSUE TITLE
The Corpus of Russian spoken by Roma

### ISSUE THREAD

**Issue by EkaterinaVoloshina** [LingConLab/conlab-server-issues#15]
Project name: The Corpus of Russian spoken by Roma
Project description: 
Tags (they are important for the later work on all projects):
Path to the project/interface: /home/evoloshina/Romani
Desired hostname: lingconlab.ru/romarus
Software (leave blank, if you don't need it):

**Comment by kirillkoncha** [comment]
Done http://lingconlab.ru/romarus/#!/

**Comment by kirillkoncha** [comment]
Если все в порядке, закройте, пожалуйста, заявку.
