### ISSUE TITLE
server unavailable

### ISSUE THREAD

**Issue by timarkh** [LingConLab/conlab-server-issues#16]
Сегодня начиная где-то с 12:00 мск сервер то не отвечает совсем, то отвечает с оочень большой задержкой.

**Comment by kirillkoncha** [comment]
У меня и Леры он нормально работает. Как сейчас с этим дела? Может быть, дело в провайдере?

**Comment by timarkh** [comment]
Да, спасибо, сейчас нормально. Наверно, тикет можно закрывать, но было бы здорово понять, в чём было дело. В провайдере -- в смысле, того места, где стоит сервер? Там же вроде что-то супернадёжное, нет? С моим провайдером, если что, всё было в порядке, проблем с доступом к другими ресурсам не было.

**Comment by kirillkoncha** [comment]
Возможно, в корпусе проводились какие-то работы и отключали электричество.

**Comment by timarkh** [comment]
Нет, это вряд ли, там аптайм 200 дней. И если бы его отключение затронуло бы какой-нибудь роутер, ответы с большой задержкой этим было бы объяснить невозможно.
