### ISSUE TITLE
Latgalian corpus

### ISSUE THREAD

**Issue by anapanifica** [LingConLab/conlab-server-issues#17]
Project name: Latgalian corpus
Project description: a pilot spoco corpus of Latgalian for Nicole Nau
Tags (they are important for the later work on all projects): spoco, corpus
Path to the project/interface: /home/apanova/Latgalian/corpus_spoco/
Desired hostname: lingconlab.ru/latgalian
Software (leave blank, if you don't need it):

**Comment by leramorozova** [comment]
сделала, проверяй

**Comment by anapanifica** [comment]
Спасибо!
