### ISSUE TITLE
Hostname for Luzhnikovo corpus

### ISSUE THREAD

**Issue by enotikk** [LingConLab/conlab-server-issues#18]
Project name: Luzhnikovo corpus
Project description: Сначала нужно удалить существующую ссылку  http://lingconlab.ru/luzhnikovo/  (она ведёт не туда)
Tags (they are important for the later work on all projects):
Path to the project/interface: /home/aazanova/Luzhnikovo
Desired hostname: lingconlab.ru/luzhnikovo
Software (leave blank, if you don't need it):

**Comment by leramorozova** [comment]
Пинганите меня в телеграме, пожалуйста, если забуду это сделать
@eternal_phobia

**Comment by kirillkoncha** [comment]
закройте, пожалуйста, тему если все сделано
