### ISSUE TITLE
issue templates

### ISSUE THREAD

**Issue by agricolamz** [LingConLab/conlab-server-issues#2]
@leramorozova, Лера, я создал issue templates, так что теперь, если пойти в issues, там есть список возможных заявок, в которых уже определена структура, назначен тег и исполнитель (в будущем, надо будет просто пойти по этим тэмплэйтам и заменить на актуальное лицо). Вместе с этим я удалил большую часть Вашего текста. Посмотрите, не удалил ли я чего важного, и пишите пожалуйста все по-английски.

Еще я сделал этот репозиторий приватным, наверное, совсем внешним людям совсем не нужно это видеть.

**Comment by agricolamz** [comment]
@leramorozova Вы снова сдлали репозиторий видимым для всех. Почему? Пусть его видят только члены организаации... А то там почты, все такое...

**Comment by leramorozova** [comment]
Потому что допускаю, что заявки будут оставлять люди, не состоящие в организации. У меня нет ощущения, что администрирование организацией тут не заброшено...

**Comment by agricolamz** [comment]
Я с этим не согласен. Достаточно много людей может добавлять людей в организацию. А так мы всему миру предоставляем возможность и посмотреть список людей, и какой софт стоит, и по какому порту заходить, и как примерно выглядит ключ... Мне это совсем не нравится.

**Comment by agricolamz** [comment]
@leramorozova ?

**Comment by agricolamz** [comment]
:(
