### ISSUE TITLE
Rogovatka corpus hostname

### ISSUE THREAD

**Issue by enotikk** [LingConLab/conlab-server-issues#20]
Project name: Rogovatka corpus
Project description: Нужен хостнейм для корпуса Роговатки на новом сервере
Tags (they are important for the later work on all projects):
Path to the project/interface: /home/aazanova/Rogovatka
Desired hostname: lingconlab.ru/rogovatka
Software (leave blank, if you don't need it):

**Comment by kirillkoncha** [comment]
done

**Comment by kirillkoncha** [comment]
Если все сделано, закройте, пожалуйста тему.
