### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by Sokureo** [LingConLab/conlab-server-issues#21]
Здравствуйте! Нужно установить новую версию Elasticsearch (7.15.0). Скачать можно здесь: https://www.elastic.co/downloads/elasticsearch

**Comment by kirillkoncha** [comment]
В процессе, поставлю докер и через него новую версию

**Comment by kirillkoncha** [comment]
done

**Comment by kirillkoncha** [comment]
если все ок, закрой, пожалуйста тему
