### ISSUE TITLE
spoken Mari corpus

### ISSUE THREAD

**Issue by Sokureo** [LingConLab/conlab-server-issues#22]
Project name: Meadow Mari Spoken Corpus
Project description: The spoken corpus of Meadow Mari
Tags (they are important for the later work on all projects): spoken_corpus, meadow_mari, tsakorpus
Path to the project/interface: /home/esokur/tsakorpus_meadow-mari_spoken/search/tsakorpus.wsgi
Desired hostname: lingconlab.ru/spoken_meadow_mari
Software (leave blank, if you don't need it):

**Comment by leramorozova** [comment]
@Sokureo Ассигни Кирилла, пожалуйста, я больше в конлабе не работаю.

**Comment by Sokureo** [comment]
@leramorozova Ассигнация автоматически происходит.

**Comment by kirillkoncha** [comment]
привет! корпус не хочет подниматься, проверь пожалуйста babel

[Sun Oct 31 18:50:28.502836 2021] [wsgi:error] [pid 273210]   warnings.warn(message, category=ElasticsearchDeprecationWarning)
[Sun Oct 31 18:50:30.247926 2021] [wsgi:error] [pid 273217] Could not compile translations with pybabel .
[Sun Oct 31 18:50:30.287040 2021] [wsgi:error] [pid 273217] /home/esokur/.local/lib/python3.8/site-packages/elasticsearch/connection/base.py:190: ElasticsearchDeprecationWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.15/security-minimal-setup.html to enable security.
[Sun Oct 31 18:50:30.287060 2021] [wsgi:error] [pid 273217]   warnings.warn(message, category=ElasticsearchDeprecationWarning)
