### ISSUE TITLE
Change project paths

### ISSUE THREAD

**Issue by Sokureo** [LingConLab/conlab-server-issues#23]
В связи с переходом на новую версию Elasticsearch, надо привязать к сайтам новые репозитории.

http://lingconlab.ru/spoken_abaza/
Old: /home/esokur/Abaza_corpus
New: /home/esokur/Abaza_corpus_tsakorpus2

http://lingconlab.ru/spoken_bashkir/
Old: /home/esokur/conlab_bashkir
New: /home/esokur/Bashkir_corpus_tsakorpus2

http://lingconlab.ru/spoken_khakas/
Old: /home/esokur/Khakas_corpus
New: /home/esokur/Khakas_corpus_tsakorpus2

http://lingconlab.ru/spoken_adyghe/
Old: /home/esokur/Spoken_Adyghe
New: /home/esokur/Spoken_Adyghe_tsakorpus2

http://lingconlab.ru/spoken_besleney/
Old: /home/esokur/Spoken_Besleney
New: /home/esokur/Spoken_Besleney_tsakorpus2

http://lingconlab.ru/cs_yakut/
Old: /home/esokur/Yakut_cs_corpus
New: /home/esokur/Yakut_cs_corpus_tsakorpus2

**Comment by kirillkoncha** [comment]
done

**Comment by kirillkoncha** [comment]
если все ок, закрой, пожалуйста тему
