### ISSUE TITLE
server access

### ISSUE THREAD

**Issue by timarkh** [LingConLab/conlab-server-issues#25]
Не могу подключиться к серверу -- пишет, что ключ не подходит (timarkh). Недавно такая же проблема была у Тимофея Мухина. Похоже на дискриминацию Тимофеев. :)

**Comment by kirillkoncha** [comment]
Здравствуйте, попробуйте сейчас.

**Comment by kirillkoncha** [comment]
@timarkh работает?

**Comment by timarkh** [comment]
Теперь работает, спасибо!
