### ISSUE TITLE
ssh access

### ISSUE THREAD

**Issue by kateabr** [LingConLab/conlab-server-issues#27]
После недавних проблем с сервером слетел доступ по ssh.

Можно добавить ключ:
```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKIdXz8RMXY95/2ShUKxEpUrPPdrrLnCZpsFPU6s9Yu0 kate@KatePC
```
в `authorized_keys` для пользователя `ebirukova`?

**Comment by kirillkoncha** [comment]
Лера Морозова больше не работает в лабе. Ассигнай меня пожалуйста по всем вопросам. Проблема может быть из-за прав доступа (нужно было сделать бэкап и я их менял чтобы скачать всей файлы). Давай я посмотрю что с ними и поменяю, если не будет работать, то добавлю ключ.

**Comment by kirillkoncha** [comment]
Попробуй сейчас подключиться

**Comment by kateabr** [comment]
Assign видимо из шаблона, я никого не назначала.

Всё работает, спасибо.
