### ISSUE TITLE
Hostname for a corpus

### ISSUE THREAD

**Issue by enotikk** [LingConLab/conlab-server-issues#28]
Project name: Vaduga dialect corpus
Project description: Corpus of a Russian dialect
Tags (they are important for the later work on all projects):
Path to the project/interface: /home/aazanova/Vaduga
Desired hostname: lingconlab.ru/vaduga
Software (leave blank, if you don't need it):

**Comment by enotikk** [comment]
Добавила все нужные папки

**Comment by kirillkoncha** [comment]
http://lingconlab.ru/vaduga/

**Comment by kirillkoncha** [comment]
закрой плиз если все ок
