### ISSUE TITLE
Corpus of Russian spoken in Manturovsky district, Kostroma oblast

### ISSUE THREAD

**Issue by EkaterinaVoloshina** [LingConLab/conlab-server-issues#29]
Project name: Corpus of Russian spoken in Manturovsky district, Kostroma oblast
Project description: Corpus of Russian dialect
Tags (they are important for the later work on all projects): 
Path to the project/interface:  /home/evoloshina/Kostroma
Desired hostname: lingconlab.ru/maturovsky
Software (leave blank, if you don't need it):

**Comment by kirillkoncha** [comment]
done (не забывайте ассигнать меня, пожалуйста, Лера не занимается этим давно, а я вижу позже, так как на почту ничего не приходит)
http://lingconlab.ru/maturovsky/#!/
