### ISSUE TITLE
DagLoans

### ISSUE THREAD

**Issue by ilchec** [LingConLab/conlab-server-issues#30]
Project name: DagLoans
Project description: The DagLoans database
Tags (they are important for the later work on all projects):
Path to the project/interface: DagLoansHSEServer
Desired hostname: lingconlab.ru/DagLoans
Software (leave blank, if you don't need it):

This is an update to the published version with the following changes: changed "Cite this project" reference, fixed double "Code" column, added published papers.

**Comment by kirillkoncha** [comment]
done

**Comment by kirillkoncha** [comment]
я перезагрузил и новая версия теперь доступна, но кажется из изменений там только в левом нижнем углу нет имени Добрушиной, а так оно осталось в how to cite this project

**Comment by ilchec** [comment]
@kirillkoncha Видимо, что-то пошло не так и новая версия не подтянулась, когда я сделал pull на сервере. У меня там несколько изменений, а на сайте явно старая версия. Можешь попробовать стянуть из моего репозитория https://github.com/ilchec/DagLoansHSEServer через git clone или просто сделать pull, или это должен делать я?

**Comment by ilchec** [comment]
@kirillkoncha Я тут пытаюсь понять, почему сервер на два коммита впереди моего репозитория и как такое может быть. И как там при этом может лежать старая версия htmlки. Но я не вижу, что лежит на сервере. Как бы мне это посмотреть просто руками? И вообще мб найдем 10 минут на зум на неделе, чтобы разобраться? В крайнем случае можно просто потереть старую папку и сделать новую.

**Comment by kirillkoncha** [comment]
@ilchec да, конечно, можно созвониться или я могу просто потереть старую папку и git clone сделать

**Comment by ilchec** [comment]
@kirillkoncha Ну давай тогда попробуем стереть и git clone.

**Comment by kirillkoncha** [comment]
done, новая версия html просто не называлась index (а старая лежала и называлась). щас новая отображается

**Comment by ilchec** [comment]
Отлично, спасибо! Действительно, теперь все хорошо выглядит.
