### ISSUE TITLE
предоставление доступа к серверу

### ISSUE THREAD

**Issue by pmashkovtseva** [LingConLab/conlab-server-issues#31]
@kirillkoncha, предоставь, пожалуйста, мне доступ к серверу lingconlab. Спасибо!

**Comment by kirillkoncha** [comment]
привет, скажи свою почту

**Comment by pmashkovtseva** [comment]
pyumashkovtseva@edu.hse.ru

**Comment by kirillkoncha** [comment]
если все ок зарой пожалуйста топик
