### ISSUE TITLE
Tserkovnoe corpus

### ISSUE THREAD

**Issue by pmashkovtseva** [LingConLab/conlab-server-issues#32]
Project name: Tserkovnoe corpus
Project description: Corpus of Russian dialect
Tags (they are important for the later work on all projects): spoken_corpus
Path to the project/interface: /home/pmashkovtseva/Tserkovnoe
Desired hostname: lingconlab.ru/tserkovnoe
Software (leave blank, if you don't need it):

**Comment by kirillkoncha** [comment]
http://lingconlab.ru/tserkovnoe/#!/
