### ISSUE TITLE
Keba corpus

### ISSUE THREAD

**Issue by pmashkovtseva** [LingConLab/conlab-server-issues#34]
Project name: Keba corpus
Project description: Corpus of Russian dialect
Tags (they are important for the later work on all projects): spoken_corpus
Path to the project/interface: /home/pmashkovtseva/Keba
Desired hostname: lingconlab.ru/keba
Software (leave blank, if you don't need it):

**Comment by kirillkoncha** [comment]
http://lingconlab.ru/keba/#!/

**Comment by kirillkoncha** [comment]
Если все ок, закрой топик, плиз
