### ISSUE TITLE
The corpus of Shetnevo and Makeevo

### ISSUE THREAD

**Issue by EkaterinaVoloshina** [LingConLab/conlab-server-issues#35]
Project name: The corpus of Shetnevo and Makeevo
Project description: the corpus of the dialect of Shetnevo and Makeevo
Tags (they are important for the later work on all projects):
Path to the project/interface: home/evoloshina/Makeevo
Desired hostname: lingconlab.ru/shetnevo
Software (leave blank, if you don't need it):

**Comment by kirillkoncha** [comment]
http://lingconlab.ru/shetnevo/#!/

**Comment by kirillkoncha** [comment]
Если все ок, закрой, пожалуйста топик
