### ISSUE TITLE
Middle Pyoza Corpus

### ISSUE THREAD

**Issue by pmashkovtseva** [LingConLab/conlab-server-issues#36]
Project name: Middle Pyoza Corpus
Project description: Corpus of Russian dialect
Tags (they are important for the later work on all projects): spoken_corpus
Path to the project/interface: /home/pmashkovtseva/Pyoza
Desired hostname: lingconlab.ru/pyoza
Software (leave blank, if you don't need it):

**Comment by kirillkoncha** [comment]
http://lingconlab.ru/pyoza
