### ISSUE TITLE
Middle Northern Dvina Corpus

### ISSUE THREAD

**Issue by pmashkovtseva** [LingConLab/conlab-server-issues#38]
Project name: Middle Northern Dvina Corpus
Project description: Corpus of Russian dialect
Tags (they are important for the later work on all projects): spoken_corpus
Path to the project/interface: /home/pmashkovtseva/Dvina
Desired hostname: lingconlab.ru/dvina
Software (leave blank, if you don't need it):

**Comment by kirillkoncha** [comment]
http://lingconlab.ru/dvina
