### ISSUE TITLE
Spoken Corpus of Muira Dargwa

### ISSUE THREAD

**Issue by Sokureo** [LingConLab/conlab-server-issues#40]
Project name: Spoken Corpus of Muira Dargwa
Project description: 
Tags (they are important for the later work on all projects): spoken_corpus, tsakorpus, dargwa, dialect
Path to the project/interface: /home/esokur/tsakorpus_muira_dargwa
Desired hostname: lingconlab.ru/muira_dargwa
Software (leave blank, if you don't need it):
Comment: проект будет доступен по ссылке lingconlab.ru/muira_dargwa/search

**Comment by kirillkoncha** [comment]
http://lingconlab.ru/muira_dargwa/search
