### ISSUE TITLE
Spoken Corpus of Kadar Dargwa

### ISSUE THREAD

**Issue by Sokureo** [LingConLab/conlab-server-issues#43]
Project name: Spoken Corpus of Kadar Dargwa
Project description:
Tags (they are important for the later work on all projects): spoken_corpus, tsakorpus, dargwa, dialect
Path to the project/interface: /home/esokur/tsakorpus_kadar_dargwa
Desired hostname: lingconlab.ru/kadar_dargwa
Software (leave blank, if you don't need it):
Comment: проект будет доступен по ссылке lingconlab.ru/kadar_dargwa/search

**Comment by kirillkoncha** [comment]
http://lingconlab.ru/kadar_dargwa/
