### ISSUE TITLE
Don Corpus

### ISSUE THREAD

**Issue by pmashkovtseva** [LingConLab/conlab-server-issues#46]
Project name: Don Corpus
Project description: Corpus of Russian dialect
Tags (they are important for the later work on all projects): spoken_corpus
Path to the project/interface: /home/pmashkovtseva/Don
Desired hostname: lingconlab.ru/don_rd
Software (leave blank, if you don't need it):

**Comment by agricolamz** [comment]
Change desired hostname: lingconlab.ru/don_rnd

**Comment by kirillkoncha** [comment]
http://lingconlab.ru/don_rnd/#!/
