### ISSUE TITLE
Parallel bible corpus

### ISSUE THREAD

**Issue by afmigoo** [LingConLab/conlab-server-issues#49]
Project name: Bible parallel corpus
Project description: We would like to have a server where we can develop this project. We are using postgres wth flask wrappen in docker
Tags (they are important for the later work on all projects): corpus, bible, parallel corpus
Path to the project/interface: github.com/affenmilchmann/parabible
Desired hostname: lingconlab.ru/parallel_bible
Software (leave blank, if you don't need it):

**Comment by agricolamz** [comment]
Путь -- это путь на сервере, что бесмысленно, пока у вас нет аккаунта на нем. Во-вторых, я бы вывешивал что-то более ли менее законченное, у меня нет такого ощущения от репозитория на гитхабе.

**Comment by afmigoo** [comment]
Я разрабатываю этот корпус не один и нам было бы удобно иметь сервер где мы будем это разворачивать для разработки и тестирования. Локально не очень удобно, тк там немаленькая база данных, которую в гит не включить. Юрий Александрович сказал, что я могу для наших целей запросить у вас доступ. Мы можем поставить там плашку "в разработке" и входить через неё по логину паролю. Но если вы всё равно против, то нет претензий, просто решил уточнить на всякий.
