### ISSUE TITLE
Yakut corpus

### ISSUE THREAD

**Issue by Sokureo** [LingConLab/conlab-server-issues#6]
Project name: Якутско-русский корпус переключения кода
Project description: Устный корпус, который содержит тексты от носителей якутского с переключением кода на русский. 
Tags (they are important for the later work on all projects): spoken corpus, code switching, languages of Russia
Path to the project/interface: ?
Desired hostname: lingconlab.ru/cs_yakut
Software (leave blank, if you don't need it): elasticsearch-5.5.0, python3: flask, lxml, html, itertools, json, gzip, time, json2cg, xlsxwriter

**Comment by leramorozova** [comment]
1. Залей проект в папку своего пользователя
2. Укажи путь до папки, в которой лежит index.html
3. Пакеты на питон надо установить через своего пользователя (через pip3 install), при необходимости создав виртуальное окружение.

UPD: свой проект (на питоне) надо запустить со своего пользователя и оставить фоново висеть.

**Comment by Sokureo** [comment]
Путь: /esokur/Yakut_cs_corpus/search/web_app/templates/index.html

**Comment by leramorozova** [comment]
Готово, проверяй:
http://lingconlab.ru/cs_yakut/search

Если все ок, то закрой тикет, пожалуйста.
