### ISSUE TITLE
Spoken Adyghe corpus

### ISSUE THREAD

**Issue by Sokureo** [LingConLab/conlab-server-issues#7]
Project name: Устный корпус адыгейского языка (темиргоевский диалект)

Project description: устный корпус адыгейского языка, который включает тексты, записанные в аулах Кабехабль, Пшичо и Хатажукай (Республика Адыгея) участниками лингвистических экспедиций РГГУ в 2006 и 2010 годах. Тексты представляют темиргоевский (чемгуйский) диалект адыгейского языка.

Tags (they are important for the later work on all projects): spoken corpus, languages of Russia, Adyghe

Path to the project/interface: /esokur/Spoken_Adyghe/search/web_app/templates/index.html

Desired hostname: lingconlab.ru/spoken_adyghe

**Comment by leramorozova** [comment]
Доступно по ссылке: http://lingconlab.ru/spoken_adyghe/
Если все хорошо, закройте, пожалуйста, заявку.
