### ISSUE TITLE
publish Spoken Besleney

### ISSUE THREAD

**Issue by Sokureo** [LingConLab/conlab-server-issues#8]
Project name: Устный корпус бесленеевского диалекта кабардино-черкесского языка

Project description: Устный бесленеевский корпус включает разножанровые тексты на бесленеевском диалекте кабардино-черкесского языка, записанные в ауле Уляп Республики Адыгея. Бесленеевский диалект - западный периферийный диалект кабардино-черкесского языка, обнаруживающий множество отличий от литературного варианта. Уляпский говор бесленеевского диалекта также активно взаимодействует с близкородственным адыгейским языком.

Tags (they are important for the later work on all projects): spoken corpus, languages of Russia, Besleney

Path to the project/interface: /esokur/Spoken_Besleney/search/web_app/templates/index.html

Desired hostname: lingconlab.ru/spoken_besleney

**Comment by leramorozova** [comment]
Проверяйте!
Если все хорошо, закройте тикет, пожалуйста.
